### PR TITLE
RIPEMD-256 implementation

### PR DESCRIPTION
**Pull request by gavadinov**
Partially addresses #1 

A RIPEMD-256 implementation based on the existing RIPEMD-320 implementation and https://android.googlesource.com/kernel/common/+/07e6124a1a46/crypto/rmd256.c. 

The test values come from - https://homes.esat.kuleuven.be/~bosselae/ripemd160.html

### CODE REVIEW

**Comment by tarcieri** [comment]
@gavadinov great! I'll take a look when I have some time to review

**Review by tarcieri — APPROVED** [review]
@gavadinov looks good!

I see you've already published the crate. Would you still like to upstream it here?

**Comment by gavadinov** [comment]
hey @tarcieri, thank you for the review. Yeah I had to publish it because I needed to use it. I would be happy to move it here and to change the ownership of the crate on crates.io.

**Comment by tarcieri** [comment]
@gavadinov fantastic. Does the code in this PR reflect what's published in the crate?

**Review by newpavlov — APPROVED** [review]
The code looks good (although I did only a cursory review), so think we can merge and publish it. But note that later we probably will merge the 3 ripemd crates into a single `ripemd` crate.

**Comment by gavadinov** [comment]
> @gavadinov fantastic. Does the code in this PR reflect what's published in the crate?

Yep it is the same. Here is the original - https://github.com/gavadinov/ripemd256 

> But note that later we probably will merge the 3 ripemd crates into a single ripemd crate.

Yeah that makes sense. There is quite a lot of duplication between the crates.

**Comment by tarcieri** [comment]
@gavadinov cool, can you add us as owners of the `ripemd256` crate?

**Comment by gavadinov** [comment]
> @gavadinov cool, can you add us as owners of the `ripemd256` crate?

Done

Also I noticed a typo in the keywords :see_no_evil: - https://github.com/RustCrypto/hashes/pull/296

**Comment by tarcieri** [comment]
Thank you!

**Pull request merged**
