### PR TITLE
keccak1600

### PR DESCRIPTION
**Pull request by kazcw**
Add a sha3 variant needed for CryptoNight.

### CODE REVIEW

**Comment by newpavlov** [comment]
Sorry for the late reply!

Looks good to me, but I would like to add tests for this varaint. Do you know if CryptoNight has published test vectors?

**Comment by kazcw** [comment]
Monero doesn't have unit tests for this function, but the full CryptoNight hash is keccak1600 chained with another hash function; so I could derive tests from the CryptoNight test vectors that will known to be correct as long as there isn't a collision of the following 32-bit hash function that happens to make wrong keccak outputs produce the right final output.

**Comment by newpavlov** [comment]
>I could derive tests from the CryptoNight test vectors

It would be great if you'll do it. You can just past them here in hex representation and I will do conversion into the binary format used by test macros.

**Comment by kazcw** [comment]
I made a special branch of my CryptoNight crate that has the inputs and outputs in hex. It tests keccak1600 outputs, and also that those keccak outputs yield the correct final hashes from Monero's test vectors. There are 4 cases based on CryptoNight v0, and 8 based on CryptoNight v2.
Source is here: https://github.com/kazcw/yellowsun/blob/test-keccak/src/lib.rs#L171

**Comment by newpavlov** [comment]
Thanks! I will port them to the binary format and add to this PR.

**Pull request merged**
