### PR TITLE
chore: Update hex-literal to 0.2

### PR DESCRIPTION
**Pull request by igor-raits**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by newpavlov** [comment]
`hex-literal v0.2` uses 2018 edition, so this PR breaks MSRV promise. I will update `hex-literal` version on v0.9 release of hash crates, which hopefully will be released this July.

**Comment by igor-raits** [comment]
Note that it is dev-dependency, so it does not really matter. but whatever :)

**Comment by tarcieri** [comment]
@ignatenkobrain it does matter, because Travis tests against pre-2018 edition versions and `hex-literal` is used in the tests

**Comment by tarcieri** [comment]
`hex-literal` has been bumped to v0.2.1 in HEAD

**Pull request closed without merging**
