### PR TITLE
Add Tiger hash

### PR DESCRIPTION
**Pull request by jmcomets**
Note that this depends on the addition of a `len_padding_with` method to
`BlockBuffer*` structs (RustCrypto/utils#7).

### CODE REVIEW

**Comment by newpavlov** [comment]
Thank you for you contribution and welcome!

I will try to look over your code in the following week.

**Comment by jmcomets** [comment]
Any updates on this?

**Comment by rawler** [comment]
Also wondering about updates on this?

**Comment by newpavlov** [comment]
Sorry for the long waiting time! I will need to introduce some minor changes before merging this PR.

**Comment by jmcomets** [comment]
Hi there! I've rebased & updated the implementation to use the new API for padding.

I noticed that while the prefix was previously an argument to `len_padding_with`, this prefix argument disappeared in [this commit](https://github.com/RustCrypto/utils/commit/d2abf4356f0230f3a134cbe3ccfb107d6d017253), after the method was renamed to [len64_padding_be](https://github.com/RustCrypto/utils/commit/582423feeafef216d5b314c9f13518ba890260f0).

Instead, the prefix was hardcoded to `0x80`, which works for version 2 of the Tiger hash...but version 1 pads with a prefix of `0x01`. I adapted the implementation to only provide version 2, but I don't understand why this prefix argument was dropped. 🤔 

Finally, since the rebase my tests no longer build. I had a look & it seems that there's an ambiguity when calling `.input(some_bytes)`. If someone could help me fix it, I'd appreciate it. 😅

**Comment by tarcieri** [comment]
@jmcomets sorry this PR has been so long in the tooth!

If you can please rebase it again and add a `.github/workflows/tiger.yml` (you can copy and paste it from another digest) I'll see to it we get this merged.

Note that we've released new versions of several of the dependencies, namely `digest` v0.9. See also #164 for a (presently WIP) `block-buffer` upgrade.

**Comment by tarcieri** [comment]
Closing in favor of #229

**Pull request closed without merging**
