### PR TITLE
Update examples to use `default()` instead of `new()` which no longer exists

### PR DESCRIPTION
**Pull request by boxbeam**
Also worth noting: `finalize()` does not appear to exist

### CODE REVIEW

**Comment by newpavlov** [comment]
The methods are part of the [`Digest`](https://docs.rs/digest/latest/digest/trait.Digest.html) trait, which is implemented through the [blanket impl](https://docs.rs/digest/latest/src/digest/digest.rs.html#57-129) for most of hashes in this repository. Also, the doctests are tested as part of our CI, so we know they are valid.

**Comment by boxbeam** [comment]
Might be good to mention that in the examples. I couldn't figure out why new() wasn't working and LSP didn't recommend the trait.

**Comment by tarcieri** [comment]
Which example are you looking at?

The one here says: https://github.com/RustCrypto/hashes#usage

> [`sha2`](https://docs.rs/sha2) and the other hash implementation crates re-export the [`digest`] crate and the [`Digest`] trait for convenience, so you don't have to include it in your `Cargo.toml` it as an explicit dependency.
>
> Now you can write the following code:
>
> ```rust
> use sha2::{Sha256, Digest};
> [...]
> ```
> [`digest`]: https://docs.rs/digest
> [`Digest`]: https://docs.rs/digest/0.10.0/digest/trait.Digest.html

**Comment by boxbeam** [comment]
I guess to me it was unclear that `new` comes from `Digest`.

**Comment by aetstapa** [comment]
Maybe other trait imported caused your problem, if so, the code below should be helpful.
```
use sha2::{Digest, Sha256};
let mut hasher: Sha256 = Digest::new();
Digest::update(&mut hasher, b"hello");
let h = Digest::finalize(hasher);
```
[https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name](url)

**Pull request closed without merging**
