### PR TITLE
Fix `ripemd160/examples/ripemd160sum.rs` to digest correct bytes.

### PR DESCRIPTION
**Pull request by ageldama**
Seemed digesting incorrect byte count.

### CODE REVIEW

**Comment by newpavlov** [comment]
Imagine `n = 0`, with your code it would result in `&buffer[..0-1]`, which is clearly incorrect.

**Comment by ageldama** [comment]
> Imagine `n = 0`, with your code it would result in `&buffer[..0-1]`, which is clearly incorrect.

Please see: https://github.com/ageldama/rust-crypto-ripemd160-example-demo
And https://md5calc.com/hash/ripemd160/foobarzoospameggs+hello%3F

```
$ echo foobarzoospameggs hello\? | cargo run --example orig
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/examples/orig`
bytes: 25
bytes: [102, 111, 111, 98, 97, 114, 122, 111, 111, 115, 112, 97, 109, 101, 103, 103, 115, 32, 104, 101, 108, 108, 111, 63, 10]
05186d956d162e87eafa89e1257c028a5211134b	-


$ echo foobarzoospameggs hello\? | cargo run --example minus1
   Compiling rust-crypto-ripemd160-example-demo v0.1.0 (/home/jhyun/P/rust-crypto-ripemd160-example-demo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/examples/minus1`
bytes: 25
bytes: [102, 111, 111, 98, 97, 114, 122, 111, 111, 115, 112, 97, 109, 101, 103, 103, 115, 32, 104, 101, 108, 108, 111, 63]
88dab20b21c4ee91157cf8c4fc925fec6ae3fe45	-
```

Hope I made the point clear. :-)

Thanks.

**Comment by newpavlov** [comment]
Your "fix" is still clearly incorrect. Your CLI examples pass a newline symbol `\n` at the end of the string. Try to create a file with your example string and pass it using `cat`. You also can add `println!("{:?}", std::str::from_utf8(&buffer[..n]));` to the code to see processed strings for yourself.

**Comment by ageldama** [comment]
> Your "fix" is still clearly incorrect. Your CLI examples pass a newline symbol `\n` at the end of the string. Try to create a file with your example string and pass it using `cat`. You also can add `println!("{:?}", std::str::from_utf8(&buffer[..n]));` to the code to see processed strings for yourself.

No, thanks.

I've already checked with a written file with this PR's changed example program,
And I don't want to care about my "examples"-repos.
Also I've already did that with some written files before. :-)

https://github.com/RustCrypto/hashes/pull/281/files

Please see the changes, I think you need to `cargo run --example` with this PR. :-)

**Comment by ageldama** [comment]
> Your "fix" is still clearly incorrect. Your CLI examples pass a newline symbol `\n` at the end of the string. Try to create a file with your example string and pass it using `cat`. You also can add `println!("{:?}", std::str::from_utf8(&buffer[..n]));` to the code to see processed strings for yourself.

Uhh! My bad.

```
$ echo -n correct horse battery staple | cargo run --example ripemd160sum
  Downloaded cpufeatures v0.1.4
  Downloaded 1 crate (10.1 KB) in 1.36s
   Compiling block-padding v0.2.1
   Compiling block-buffer v0.9.0
   Compiling ripemd160 v0.9.1 (/home/jhyun/P/RustCrypto-hashes/ripemd160)
    Finished dev [optimized + debuginfo] target(s) in 2.93s
     Running `target/debug/examples/ripemd160sum`
5e708aa85ae8b0d080837c50bd63634d584edc00	-
```

Thanks.

**Pull request closed without merging**
