### PR TITLE
Fix `KeyInit` for blake2

### PR DESCRIPTION
**Pull request by vlad9486**
Right now it is crashes always on `KeyInit::new`.

### CODE REVIEW

**Comment by newpavlov** [comment]
Your changes are incorrect, you try to pass key as salt. How exactly does it crash?

**Comment by vlad9486** [comment]
@newpavlov 

Now it is crashing:

```
#[cfg(test)]
#[test]
fn blake2b_trivial() {
    use blake2::{Blake2bMac512, digest::KeyInit};

    <Blake2bMac512 as KeyInit>::new(&Default::default());
}
```

Because it is your code is incorrect and passing key as salt. My fix is fixing that. And the mentioned test is passing.

**Comment by vlad9486** [comment]
@newpavlov 
Please, look again. The original code is incorrect and passing key as salt. My fix is fixing that. Here is the test, which is crashed #433.

**Comment by newpavlov** [comment]
Oh... True. We have tests for the MAC types, but they different codepath.

**Pull request merged**
