### PR TITLE
Fix SHA3 performance degradation

### PR DESCRIPTION
**Pull request by aewag**
Related issue #468 

@Slixe Could you please give this branchof the SHA3 crate a try and see if it fixes the performance degradation?

If it does, I would finalize it and mark it as ready.

### CODE REVIEW

**Comment by Slixe** [comment]
LGTM.

v1.0.6:
~ 10 MH/s

v1.0.7 (bug introduced):
~ 4 MH/s

This pull request seems to fix it because I'm at ~ 10 MH/s with it again.

Thanks for your work :slightly_smiling_face:

**Comment by tarcieri** [comment]
@aewag if you can remove WIP/draft we can get this merged

**Comment by aewag** [comment]
> @aewag if you can remove WIP/draft we can get this merged

will do. just one question: shall the sha3 crate take the `keccak` from git or do you plan to release a patch?

**Comment by tarcieri** [comment]
@aewag `keccak` v0.1.4 has been released

**Comment by aewag** [comment]
@tarcieri nice, just updated the PR and flagged it as ready

**Pull request merged**
