### PR TITLE
ripemd: Add OID support

### PR DESCRIPTION
**Pull request by lumag**
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>

### CODE REVIEW

**Comment by newpavlov** [comment]
We need to have an explicit decision on the issue described in #408 before implementing OID support for RIPEMD hashes.

**Comment by lumag** [comment]
@newpavlov let's have this PR open and move the discussion to the mentioned issue. Marking this PR as a draft to prevent merging.

**Comment by newpavlov** [comment]
Regardless of our choice, I think it's worth to add a note about existence of multiple OIDs with reference to the issue.

**Comment by lumag** [comment]
@newpavlov done

**Pull request merged**
