### PR TITLE
sha2: fix aarch64 implementation being disabled

### LINKED ISSUE #568: sha2: aarch64 acceleration broken on master
#542 removed the sha2-asm and asm feature, which incidentally also made the aarch64 code dead, because it is behind a `#[cfg(all(feature = "asm", target_arch = "aarch64"))]` (https://github.com/RustCrypto/hashes/blob/c38787b7abd8dd10412972941d077df54c95a4bb/sha2/src/sha256.rs#L9) — since that feature is no longer declared in Cargo.toml, it cannot be enabled.

I suspect this isn't intentional, because the looongarch implementation also uses inline assembly but isn't disabled.

### PR DESCRIPTION
**Pull request by enkore**
Fixes #568 

(eref 42d478fb6976)

### CODE REVIEW

**Comment by tarcieri** [comment]
Thanks!

**Comment by enkore** [comment]
works quite well, too: on a GH200 the aarch64.rs code runs at 1.7 GiB/s (versus 0.4 GiB/s for the soft implementation), OpenSSL 3 is just shy of 2 GiB/s.

**Comment by tarcieri** [comment]
We can probably switch from inline ASM back to the intrinsics at this point, given the current MSRV

**Comment by enkore** [comment]
Looks like these only landed in 1.76: https://doc.rust-lang.org/core/arch/aarch64/fn.vsha256su0q_u32.html

**Comment by tarcieri** [comment]
I couldn't even get them to work on 1.76, despite the documentation making it look like they should work: https://github.com/RustCrypto/hashes/actions/runs/8251432049/job/22568457459

**Comment by tarcieri** [comment]
Oh, perhaps the SHA-256 intrinsics were stabilized, but the SHA-512 ones weren't?

**Comment by enkore** [comment]
Looks like it, that's a bit odd.

**Comment by tarcieri** [comment]
Here's the stabilization PR: https://github.com/rust-lang/stdarch/pull/1399/files

I don't even see where e.g. `vsha512h2q_u64` is defined? Edit: aha, here it is:

https://github.com/rust-lang/stdarch/blob/3961d3b/crates/core_arch/src/aarch64/neon/generated.rs#L15274-L15288

Gated under `stdarch_neon_sha3`. Tracking issue here: https://github.com/rust-lang/rust/issues/117225

**Comment by tarcieri** [comment]
Opened #571 to track this

**Pull request merged**
