### PR TITLE
[WIP] sha1: add x86 intrinsics support

### PR DESCRIPTION
**Pull request by newpavlov**
On Ryzen 7 2700X I get up to 2.2 GB/s. For now CPUID detection is absent. I plan to add it based on the approach used in `getrandom`.

Unfortunately GitHub Actions workers do not have SHA instructions, so we will not be able to properly test this code in CI.

@linkmauve
Can you please check that I haven't broke ARM code?

### CODE REVIEW

**Comment by newpavlov** [comment]
Closed in favor of #167.

**Comment by linkmauve** [comment]
Hi, why are you removing runtime feature detection?  Very often the code will be built for a generic CPU and will run on one with those extensions (on ARM at least).

**Comment by newpavlov** [comment]
I am not removing it, it's just not implemented in the draft PR yet.

**Comment by newpavlov** [comment]
And ARM detection works without changes (at least it should).

**Pull request closed without merging**
