### PR TITLE
Turn Keccak256Full comment into docs

### PR DESCRIPTION
**Pull request by felixrabe**
/// Docs...
    item

is equivalent to:

    #[doc="Docs..."]
    item

See https://stackoverflow.com/a/33999625/1034080 for an example.

### CODE REVIEW

**Comment by newpavlov** [comment]
Looks good! I will appreciate if you also will make `meta` argument a required one and will add docs for other types.

**Comment by felixrabe** [comment]
- [x] Make `meta` argument required.
- [ ] Add docs for other types.

I'll have a look.

**Comment by newpavlov** [comment]
BTW you also can pass docstrings only, see for example `vardoc` and `doc` macro argumetns in [BLAKE2](https://github.com/RustCrypto/hashes/blob/master/blake2/src/blake2.rs).

**Comment by felixrabe** [comment]
Ok, changed the macro argument from `$meta:meta` to `$doc:expr` and put it to the end, so the macro invocations still more or less line up.

About the empty docs for the other types: I don't really know SHA-3 and Keccak well enough, nor do I have the energy to research them ATM (I got stuck yesterday reading half of HN about pros and cons of SHA-2 and SHA-3).

Do you have any other input for me about the proposed changes here? Otherwise I suggest you merge it and fill in the blanks yourself.

**Comment by newpavlov** [comment]
No problem, I will add docs a bit later! Thank you!

**Pull request merged**
