### PR TITLE
Release sha2 v0.9.7

### PR DESCRIPTION
**Pull request by newpavlov**

### CODE REVIEW

**Comment by jplatte** [comment]
@newpavlov @tarcieri This release broke Sha384, please yank!

I created a minimal reproduction as a private repo and invited you both to see it. It might only affect some inputs (there is a working test for sha384 in this repo afterall). This breakage was brought to my attention in SQLx'es Discord (not sure whether [this link](https://discord.com/channels/665528275556106240/665528275556106243/885300653679861810) works) because SQLx hashes migration scripts to make sure exactly that migration was applied.

**Comment by tarcieri** [comment]
I've gone ahead and yanked this out of caution.

I will investigate and see if I can reproduce the problem. If I can, I'll file a @RustSec advisory.

**Comment by newpavlov** [comment]
Oh, sorry about that!

`force-soft` works without issues and you don't use the `asm` feature, correct?

cc @Rexagon

**Comment by tarcieri** [comment]
FWIW I wasn't able to reproduce this problem

**Comment by newpavlov** [comment]
@tarcieri 
Just to be sure: are you running it on an x86-64 CPU with AVX2?

**Comment by tarcieri** [comment]
Yes, Intel Core i9

**Comment by newpavlov** [comment]
I was able to reproduce this bug. Looks like there is a problem in the AVX2 part. If we are processing blocks one by one, then the AVX code works correctly.

**Comment by tarcieri** [comment]
Aah, it's possible the input message I used to test wasn't long enough

**Pull request merged**
