### PR TITLE
Add shabal hash

### PR DESCRIPTION
**Pull request by spebern**

### CODE REVIEW

**Comment by spebern** [comment]
Any news on this one?

**Comment by tarcieri** [comment]
@spebern thanks! (apologies for the belated response)

Would it be possible for you to add the @RustCrypto/hashes team as an owner of the crate?

**Comment by spebern** [comment]
Sorry I somehow missed your message. I added you as an owner. Is there a username for @RustCrypto/hashes on crates.io that I can add?

**Comment by tarcieri** [comment]
Awesome, thank you! I can add the RustCrypto team

**Comment by spebern** [comment]
Thank you for taking care of all that! I really appreciate the work that is put into the crypto crates!

**Pull request merged**
