### PR TITLE
blake2bp/blake2sp

### PR DESCRIPTION
**Pull request by kazcw**
No-std (single-threaded) implementation.

Tests included are the official test vectors plus a long-input case.

cf. #31

### CODE REVIEW

**Comment by newpavlov** [comment]
Thank you! Can you please fix the CI failures? Looks like you are not handling big-endian correctly and use absolute path which do not work in Rust 1.21.

**Comment by kazcw** [comment]
Fixed the bugs; also added bp/sp benchmarks.

**Comment by tarcieri** [comment]
@kazcw are you still interested in landing this and if so, can you rebase please?

**Comment by kazcw** [comment]
@tarcieri Upstream has seen enough change in the last year and a half that I think it would be easier to start over than reconcile this.

**Pull request closed without merging**
